### ISSUE TITLE
Could you make a executable?

### ISSUE THREAD

**Issue by yuifu** [manabu/dockerlayer#1]
dockerlayer is awesome!!

However, I usually don't use Golang.
It would be very helpful if you kindly make a executable for Linux environments.

**Comment by manabu** [comment]
Thanks !

Current stable version is here

* [Release 0.1.3 · manabu/dockerlayer](https://github.com/manabu/dockerlayer/releases/tag/0.1.3)

And you can download.

And I update top page README

* [manabu/dockerlayer: Display some docker layer information](https://github.com/manabu/dockerlayer)
